apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: devops-agent-blueprint
    project_properties:
      deployment_region: us-east-1
      environment: dev
      owner: platform-team
      project_name: devops-agent-blueprint
  description: IaC project for devops-agent-blueprint
  name: devops-agent-blueprint
  space: bco
  tags:
  - devops
  - devsecops
  - iac
  - terraform
  - terragrunt
  - module
  - aws
  - cloud
  - automation
  - template
spec:
  lifecycle: production
  owner: IaCPlatform
  system: IaCPlatform
  type: template
